create table if not exists public.worksheet_results (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 student_name text not null,
 standard text,
 worksheet text,
 score integer not null,
 total integer not null,
 answers jsonb
);
alter table public.worksheet_results enable row level security;
create policy "allow anonymous result inserts" on public.worksheet_results for insert to anon with check (true);
